export const CONTROLLER_DECORATORS = 'CONTROLLER_DECORATORS'
export const SERVICE_DECORATORS = 'SERVICE_DECORATORS'

export const CANVAS_DECORATOR = 'CANVAS_DECORATOR'
export const CTX_DECORATOR = 'CTX_DECORATOR'
export const STATE_DECORATOR = 'STATE_DECORATOR'
export const DRAW_DECORATOR = 'DRAW_DECORATOR'
export const EVENT_EMMITER_DECORATOR = 'EVENT_EMMITER_DECORATOR'
export const EVENT_DECORATOR = 'EVENT_DECORATOR'

export const EVENT_EMMITER = 'EVENT_EMMITER'
export const ACTION = 'ACTION'
export const HASSTATE = 'HASSTATE'
